### ISSUE TITLE
asarmon source or linux binary

### ISSUE THREAD

**Issue by ffaadd** [spannerisms/jpdasm#1]
Sorry, it's not really an Issue of this repository but I can't find the source code of the special asarmon version included as windows binary. With asar itself it's not possible to assemble the files in this repository. 

Do you have a link to the asarmon sourcecode, the source itself or a linux binary?

**Comment by dwaggone** [comment]
You could try this:
https://github.com/MathOnNapkins/asar/commits/pool

Someone may have a more up to date version. I just handed a binary off to spannerisms and didn't merge it into the master branch, by the looks of it.

**Comment by ffaadd** [comment]
Thank you. I had to add #include &lt;string> to assembleblock.cpp, but beside of that everything works and I am able to build a rom with the correct crc32.
